In [25]:
import pandas as pd

In [32]:
df = pd.read_csv('../doc/prop_gender.csv')
df

       f     h
0   16.9  18.8
1    5.8   6.6
2    5.4   5.9
3    5.4   5.7
4    6.0   6.1
5    6.3   6.4
6    6.0   6.2
7    6.6   6.9
8    6.5   6.7
9    6.5   6.5
10   6.2   6.0
11   5.9   5.7
12   5.4   5.0
13  11.2   7.7

In [35]:
p_gender = {'h': {}, 'f': {}}
for i, row in df.iterrows():
    pre = 0 if i == 0 else 15 + 5 * (i - 1)
    for g in ['h', 'f']:
        p_gender[g][pre] = row[g]
        
print(p_gender)

{'h': {0: 18.8, 15: 6.6, 20: 5.9, 25: 5.7, 30: 6.1, 35: 6.4, 40: 6.2, 45: 6.9, 50: 6.7, 55: 6.5, 60: 6.0, 65: 5.7, 70: 5.0, 75: 7.7}, 'f': {0: 16.9, 15: 5.8, 20: 5.4, 25: 5.4, 30: 6.0, 35: 6.3, 40: 6.0, 45: 6.6, 50: 6.5, 55: 6.5, 60: 6.2, 65: 5.9, 70: 5.4, 75: 11.2}}

In [36]:
f80 = 6 * .65
h80 = 6 * .35

p_gender['f'][75] = p_gender['f'][75] - f80
p_gender['h'][75] = p_gender['h'][75] - h80
p_gender['f'][80] = f80
p_gender['h'][80] = h80

In [38]:
for g in ['h', 'f']:
    p_gender[g] = {k: round(v, 1) for k, v in p_gender[g].items()}

In [42]:
import json

with open('../data/p_gender_pop.json', 'w') as f:
    json.dump(p_gender, f)

In [ ]:
tr = {}
tr['h_0_infected_hosp'] = (.06, .1, .2)
tr['f_0_infected_hosp'] = (.009, .05, .2)
tr['h_0_hosp_icu'] = None
tr['f_0_hosp_icu'] = None

In [14]:
names_0 = ['h_0_infected_hosp', 'f_0_infected_hosp', 'h_0_hosp_icu', 'f_0_hosp_icu']
for age in range(7):  
    for tr in ['infected_hosp', 'hosp_icu']:
        for g in ['h', 'f']:
            names_0.append(f'{g}_{10 * (age+2)}_{tr}')
        
print(names_0)

['h_0_infected_hosp', 'f_0_infected_hosp', 'h_0_hosp_icu', 'f_0_hosp_icu', 'h_20_infected_hosp', 'f_20_infected_hosp', 'h_20_hosp_icu', 'f_20_hosp_icu', 'h_30_infected_hosp', 'f_30_infected_hosp', 'h_30_hosp_icu', 'f_30_hosp_icu', 'h_40_infected_hosp', 'f_40_infected_hosp', 'h_40_hosp_icu', 'f_40_hosp_icu', 'h_50_infected_hosp', 'f_50_infected_hosp', 'h_50_hosp_icu', 'f_50_hosp_icu', 'h_60_infected_hosp', 'f_60_infected_hosp', 'h_60_hosp_icu', 'f_60_hosp_icu', 'h_70_infected_hosp', 'f_70_infected_hosp', 'h_70_hosp_icu', 'f_70_hosp_icu', 'h_80_infected_hosp', 'f_80_infected_hosp', 'h_80_hosp_icu', 'f_80_hosp_icu']

In [1]:
hosp_icu = [(0.1, 0.06, 0.2), (0.09, 0.05, 0.2), (17.5, 13.8, 22.0), (8.5, 5.8, 12.1), (0.6, 0.3, 1.0), 
 (0.5, 0.3, 0.8), (12.2, 10.0, 14.8), (6.8, 5.1, 8.9), (1.2, 0.6, 2.0), (0.9, 0.5, 1.5), 
 (17.2, 15.2, 19.3), (10.4, 8.8, 12.2), (1.6, 0.9, 2.7), (1.3, 0.7, 2.2), (24.3, 22.5, 26.3), 
 (14.3, 12.8, 15.9), (3.2, 1.7, 5.3), (2.5, 1.4, 4.2), (31.7, 30.0, 33.4), (19.0, 17.7, 20.4), 
 (7.0, 3.7, 11.7), (5.3, 2.8, 8.8), (36.4, 34.8, 38.1), (21.6, 20.3, 22.9), (11.4, 6.1, 19.0), 
 (8.0, 4.3, 13.4), (29.0, 27.7, 30.3), (17.0, 16.0, 18.1), (31.4, 16.7, 52.6), (15.9, 8.5, 26.5), 
 (5.7, 5.2, 6.1), (3.4, 3.0, 3.8)]

In [21]:
names_1 = ['h_0_hosp_death', 'f_0_infected_death', 'h_0_hosp_death', 'f_0_infected_death']
for age in range(7):  
    for tr in ['hosp_death', 'infected_death']:
        for g in ['h', 'f']:
            names_1.append(f'{g}_{10 * (age+2)}_{tr}')
        
print(names_1)

['h_0_hosp_death', 'f_0_infected_death', 'h_0_hosp_death', 'f_0_infected_death', 'h_20_hosp_death', 'f_20_hosp_death', 'h_20_infected_death', 'f_20_infected_death', 'h_30_hosp_death', 'f_30_hosp_death', 'h_30_infected_death', 'f_30_infected_death', 'h_40_hosp_death', 'f_40_hosp_death', 'h_40_infected_death', 'f_40_infected_death', 'h_50_hosp_death', 'f_50_hosp_death', 'h_50_infected_death', 'f_50_infected_death', 'h_60_hosp_death', 'f_60_hosp_death', 'h_60_infected_death', 'f_60_infected_death', 'h_70_hosp_death', 'f_70_hosp_death', 'h_70_infected_death', 'f_70_infected_death', 'h_80_hosp_death', 'f_80_hosp_death', 'h_80_infected_death', 'f_80_infected_death']

In [5]:
dh_ifp = [(1.2, 0.4, 2.8), (0.0, 0.0, 0.0), (0.001, 0.0, 0.004), (0.0, 0.0, 0.0), (1.3, 0.6, 2.4), 
 (1.4, 0.6, 2.7), (0.007, 0.003, 0.02), (0.007, 0.002, 0.02), (2.5, 1.8, 3.4), (1.6, 0.9, 1.4), 
 (0.03, 0.01, 0.05), (0.01, 0.006, 0.03), (3.9, 3.1, 4.7), (3.2, 2.5, 4.1), (0.06, 0.03, 0.1), 
 (0.04, 0.02, 0.07), (7.5, 66.0, 8.3), (6.4, 5.6, 7.2), (0.2, 0.1, 0.4), (0.2, 0.08, 0.3), 
 (14.2, 16.2, 15.3), (12.0, 11.0, 13.1), (1.0, 0.5, 1.7), (0.6, 0.3, 1.1), (25.3, 24.1, 26.6), 
 (20.7, 19.5, 22.0), (2.9, 1.5, 4.8), (1.7, 0.9, 2.8), (42.0, 40.7, 43.4), (34.0, 32.7, 35.4), 
 (13.2, 7.0, 22.1), (5.4, 2.9, 9.1)]

In [11]:
demographies = ['h_0', 'f_0']
for age in range(7):
    for g in ['h', 'f']:
            demographies.append(f'{g}_{10 * (age+2)}')

In [12]:
demographies

['h_0',
 'f_0',
 'h_20',
 'f_20',
 'h_30',
 'f_30',
 'h_40',
 'f_40',
 'h_50',
 'f_50',
 'h_60',
 'f_60',
 'h_70',
 'f_70',
 'h_80',
 'f_80']

In [18]:
transitions = {'infected_hosp': [], 'hosp_icu': [], 'hosp_death': [], 'infected_death': []}

for i in range(len(names_0)):
    transition = '_'.join(names_0[i].split('_')[-2:])
    transitions[transition].append(hosp_icu[i][0])
    
transitions

{'infected_hosp': [0.1,
  0.09,
  0.6,
  0.5,
  1.2,
  0.9,
  1.6,
  1.3,
  3.2,
  2.5,
  7.0,
  5.3,
  11.4,
  8.0,
  31.4,
  15.9],
 'hosp_icu': [17.5,
  8.5,
  12.2,
  6.8,
  17.2,
  10.4,
  24.3,
  14.3,
  31.7,
  19.0,
  36.4,
  21.6,
  29.0,
  17.0,
  5.7,
  3.4],
 'hosp_death': [],
 'infected_death': []}

In [22]:
for i in range(len(names_1)):
    transition = '_'.join(names_1[i].split('_')[-2:])
    transitions[transition].append(dh_ifp[i][0])
    
transitions

{'infected_hosp': [0.1,
  0.09,
  0.6,
  0.5,
  1.2,
  0.9,
  1.6,
  1.3,
  3.2,
  2.5,
  7.0,
  5.3,
  11.4,
  8.0,
  31.4,
  15.9],
 'hosp_icu': [17.5,
  8.5,
  12.2,
  6.8,
  17.2,
  10.4,
  24.3,
  14.3,
  31.7,
  19.0,
  36.4,
  21.6,
  29.0,
  17.0,
  5.7,
  3.4],
 'hosp_death': [1.2,
  0.001,
  1.3,
  1.4,
  2.5,
  1.6,
  3.9,
  3.2,
  7.5,
  6.4,
  14.2,
  12.0,
  25.3,
  20.7,
  42.0,
  34.0],
 'infected_death': [0.0,
  0.0,
  0.007,
  0.007,
  0.03,
  0.01,
  0.06,
  0.04,
  0.2,
  0.2,
  1.0,
  0.6,
  2.9,
  1.7,
  13.2,
  5.4]}

In [23]:
transitions['demography'] = demographies

In [27]:
df_transitions = pd.DataFrame(transitions)

In [28]:
df_transitions

    infected_hosp  hosp_icu  hosp_death  infected_death demography
0            0.10      17.5       1.200           0.000        h_0
1            0.09       8.5       0.001           0.000        f_0
2            0.60      12.2       1.300           0.007       h_20
3            0.50       6.8       1.400           0.007       f_20
4            1.20      17.2       2.500           0.030       h_30
5            0.90      10.4       1.600           0.010       f_30
6            1.60      24.3       3.900           0.060       h_40
7            1.30      14.3       3.200           0.040       f_40
8            3.20      31.7       7.500           0.200       h_50
9            2.50      19.0       6.400           0.200       f_50
10           7.00      36.4      14.200           1.000       h_60
11           5.30      21.6      12.000           0.600       f_60
12          11.40      29.0      25.300           2.900       h_70
13           8.00      17.0      20.700           1.700       f_70
14          31.40       5.7      42.000          13.200       h_80
15          15.90       3.4      34.000           5.400       f_80

In [33]:
for colname in ['infected_hosp', 'hosp_icu', 'hosp_death', 'infected_death']:
    df_transitions[colname] = df_transitions[colname] * 100
    
df_transitions

    infected_hosp  hosp_icu  hosp_death  infected_death demography
0          0.0010     0.175     0.01200         0.00000        h_0
1          0.0009     0.085     0.00001         0.00000        f_0
2          0.0060     0.122     0.01300         0.00007       h_20
3          0.0050     0.068     0.01400         0.00007       f_20
4          0.0120     0.172     0.02500         0.00030       h_30
5          0.0090     0.104     0.01600         0.00010       f_30
6          0.0160     0.243     0.03900         0.00060       h_40
7          0.0130     0.143     0.03200         0.00040       f_40
8          0.0320     0.317     0.07500         0.00200       h_50
9          0.0250     0.190     0.06400         0.00200       f_50
10         0.0700     0.364     0.14200         0.01000       h_60
11         0.0530     0.216     0.12000         0.00600       f_60
12         0.1140     0.290     0.25300         0.02900       h_70
13         0.0800     0.170     0.20700         0.01700       f_70
14         0.3140     0.057     0.42000         0.13200       h_80
15         0.1590     0.034     0.34000         0.05400       f_80

In [34]:
df_transitions.to_csv('../data/df_transitions.csv', index=False)

In [72]:
s = """
7.0
(3.7-11.7) 5.3 (2.8-
8.8) 6.1 (3.2-
10.2)
"""

v = []
for line in s.split('\n')[1:-1]:
    line = line.replace('(', '').replace(')', '').replace('-', ' ').split(' ')
    line = [float(f) for f in line if len(f) > 0]
    print(line)
    v += line

print(f'v: {v}')
res = [[v[3*i+j] for j in range(3)] for i in range(int(len(v)/3))]
res = str(res)[1:-1].replace('[', '(').replace(']', ')')
print(res)

[7.0]
[3.7, 11.7, 5.3, 2.8]
[8.8, 6.1, 3.2]
[10.2]
v: [7.0, 3.7, 11.7, 5.3, 2.8, 8.8, 6.1, 3.2, 10.2]
(7.0, 3.7, 11.7), (5.3, 2.8, 8.8), (6.1, 3.2, 10.2)

In [107]:
s = """
25.3 (24.1-
26.6) 20.7 (19.5-
22.0) 23.2 (22.3-
24.1) 2.9 (1.5-
4.8) 1.7
(0.9-2.8) 2.2
(1.2-3.7)
80+ 42.0 (40.7-
43.4) 34.0 (32.7-
35.4) 38.4 (37.4-
39.3) 13.2 (7.0-
22.1) 5.4
(2.9-9.1) 8.3 (4.4-
13.9)
"""

In [108]:
import re

v = []
for line in s.split('\n')[1:-1]:
    figs = re.findall('\d+\.\d+', line)
    v += [float(fig) for fig in figs]
    
print(v)
print()
    
res = [[v[3*i+j] for j in range(3)] for i in range(int(len(v)/3))]
print(res)
res = [res[i] for i in range(len(res)) if (i+1)%3 != 0]
res = str(res)[1:-1].replace('[', '(').replace(']', ')')
print()
print(res)

[25.3, 24.1, 26.6, 20.7, 19.5, 22.0, 23.2, 22.3, 24.1, 2.9, 1.5, 4.8, 1.7, 0.9, 2.8, 2.2, 1.2, 3.7, 42.0, 40.7, 43.4, 34.0, 32.7, 35.4, 38.4, 37.4, 39.3, 13.2, 7.0, 22.1, 5.4, 2.9, 9.1, 8.3, 4.4, 13.9]

[[25.3, 24.1, 26.6], [20.7, 19.5, 22.0], [23.2, 22.3, 24.1], [2.9, 1.5, 4.8], [1.7, 0.9, 2.8], [2.2, 1.2, 3.7], [42.0, 40.7, 43.4], [34.0, 32.7, 35.4], [38.4, 37.4, 39.3], [13.2, 7.0, 22.1], [5.4, 2.9, 9.1], [8.3, 4.4, 13.9]]

(25.3, 24.1, 26.6), (20.7, 19.5, 22.0), (2.9, 1.5, 4.8), (1.7, 0.9, 2.8), (42.0, 40.7, 43.4), (34.0, 32.7, 35.4), (13.2, 7.0, 22.1), (5.4, 2.9, 9.1)